[[constraint]]
  name = "github.com/gliderlabs/logspout"
  version = "3.2.6"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.4.0"

[prune]
  go-tests = true
  unused-packages = true
