[[constraint]]
  name = "github.com/gliderlabs/logspout"
  version = "3.2.4"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"

[prune]
  go-tests = true
  unused-packages = true
