[[constraint]]
  name = "github.com/gliderlabs/logspout"
  version = "3.2.11"

[[constraint]]
  name = "github.com/slack-go/slack"
  version = "0.6.5"

[prune]
  go-tests = true
  unused-packages = true
